In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'2.4.1'

In [5]:
x = torch.randn(3, requires_grad=True)

In [6]:
x

tensor([ 1.3712, -1.5540,  0.8804], requires_grad=True)

In [8]:
y = x+2
print(y)

tensor([3.3712, 0.4460, 2.8804], grad_fn=<AddBackward0>)


In [9]:
z = 2*y*y
print(z)

tensor([22.7301,  0.3978, 16.5939], grad_fn=<MulBackward0>)


In [10]:
w = y*y + 2*y 

In [11]:
w

tensor([18.1075,  1.0909, 14.0578], grad_fn=<AddBackward0>)

In [12]:
z = z.mean()

In [13]:
z

tensor(13.2406, grad_fn=<MeanBackward0>)

In [14]:
z.backward()

In [15]:
print(x.grad)

tensor([4.4949, 0.5947, 3.8406])
